key: "personalized_item_recommendation"
description: ''
dataConfigs:
  - displayName: 'User Feature Data'
    key: user_feature_data
    description: ''
    configurations:
    - displayName: 'User Feature Columns'
      key: user_feature_columns
      type: Columns
      value: []
      required: True
  #    constraints: []
      description: ''
    - displayName: 'User ID Column'
      key: user_id_column
      type: Column
      value: null
      required: True
  #    constraints: []
      description: ''
  #  constraints: []
  - displayName: 'Item Feature Data'
    key: item_feature_data
    description: ''
    configurations:
      - displayName: 'Item Feature Columns'
        type: Columns
        key: item_feature_columns
        value: []
        required: True
  #      constraints: []
        description: ''
      - displayName: 'Item ID Column'
        type: Column
        key: item_id_column
        value:
        required: True
  #      constraints: []
        description: ''
  #  constraints: []
  - displayName: 'User-Item Interaction Data'
    key: user_item_interaction_data
    description: ''
    configurations:
      - displayName: 'User ID Column'
        type: Column
        key: user_id_column
        value: null
        required: True
  #      constraints: []
        description: ''
      - displayName: 'Item ID Column'
        type: Column
        key: item_id_column
        value: null
        required: True
  #      constraints: []
        description: ''
      - displayName: 'Rating Column'
        type: Column
        key: rating_column
        value: null
        required: False
  #      constraints: []
        description: ''
      - displayName: 'TimeStamp Column'
        type: Column
        key: timestamp_column
        value: null
        required: False
  #      constraints: []
        description: ''
  #  constraints:
  #    - dataKey: user_item_interaction_data
  #      key: user_item_interaction_data
  #      type: Data
  #      constraint: RecordNumberConstraint
  #      value: 100_000